language: python

python:
  - "2.7"

install:
  - pip install flake8 coverage coveralls
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database timemap;' -U postgres

script:
  - flake8 --ignore=E501 .
  - coverage run manage.py test

after_success: coveralls

notifications:
  slack: eldarion:WclbY0MPWcDjwqmdYaCzPCu7
