language: python

python:
  - "2.7"

install:
  - pip install flake8 coverage coveralls
  - pip install -r requirements.txt

script:
  - flake8
  - coverage run manage.py test

after_success: coveralls

notifications:
  slack: eldarion:WclbY0MPWcDjwqmdYaCzPCu7
